# permissions for end users to view mystatefulsets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: mystatefulset-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: devops-golang-test
    app.kubernetes.io/part-of: devops-golang-test
    app.kubernetes.io/managed-by: kustomize
  name: mystatefulset-viewer-role
rules:
- apiGroups:
  - apps.example.com
  resources:
  - mystatefulsets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.example.com
  resources:
  - mystatefulsets/status
  verbs:
  - get
